### ISSUE TITLE
AttributeError: 'Phase' object has no attribute 'state'

### ISSUE THREAD

**Issue by zhuliwen** [docwza/sumolights#15]
```
start running main...
networks/double.net.xml
SUCCESSFULLY GENERATED NET DATA
 Retrying in 1 seconds
Loading configuration... done.
Traceback (most recent call last):
  File "run.py", line 17, in <module>
    main()
  File "run.py", line 10, in main
    distprocs = DistProcs(args, args.tsc, args.mode)
  File "/home/zlw/PycharmProjects/sumolights/src/distprocs.py", line 71, in __init__
    netdata = sim.update_netdata()
  File "/home/zlw/PycharmProjects/sumolights/src/sumosim.py", line 120, in update_netdata
    tl_junc = self.get_traffic_lights()
  File "/home/zlw/PycharmProjects/sumolights/src/sumosim.py", line 94, in get_traffic_lights
    green_phases = [ p.state for p in logic.getPhases()
  File "/home/zlw/PycharmProjects/sumolights/src/sumosim.py", line 95, in <listcomp>
    if 'y' not in p.state
AttributeError: 'Phase' object has no attribute 'state'
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error).

```
my sumo version is 1.2.0

**Comment by docwza** [comment]
Try updating to the newest version of [SUMO](https://sumo.dlr.de/docs/Downloads.php#linux_binaries), if the issue persists reopen the issue.
